version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gocritic
    - misspell
    - revive
    - unconvert
    - unparam

  settings:
    revive:
      rules:
        - name: var-naming
        - name: exported
          arguments:
            - disableStutteringCheck
        - name: error-return
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
          disabled: true
        - name: unreachable-code
        - name: redefines-builtin-id

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - bodyclose
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports
